name: msmarco-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - tqdm>=4.65.0
  - requests>=2.26.0
  - datasets
  - pip
  - pip:
  - ipykernel # Optional: for Jupyter notebook support